### ISSUE TITLE
Don't rebuild the same HEAD multiple days running

### ISSUE THREAD

**Issue by dra27** [ocaml-dune/binary-distribution#45]
It is wasteful to rebuild Dune when the head commit hasn't actually changed - e.g. 2024-09/26/2024-09-27/2024-09-28 (17071ec), 2024-09-21/2024-09-20 (d6f1a274) and 2024-09-19/2024-09-20 (3f31387ec).

**Comment by mtelvers** [comment]
Looks straightforward.  See https://github.com/orgs/community/discussions/27128

**Comment by Leonidas-from-XIV** [comment]
I agree that it would be good to deduplicated it, because over the weekend we have a lot of nightlies that are identical and it is not a good user experience to look for an older version and having to click through the list until they find one that's actually from a different commit.

What I don't like about the linked solutions is that they just check whether there was a commit in the last 24h, because if a run is missed for random reasons (network failure, some other issue), then an old version will stay up until the next commit which sometimes can take a few days.

**Comment by Leonidas-from-XIV** [comment]
Fixed by #76.
